### ISSUE TITLE
UI components broken on v142+

### ISSUE THREAD

**Issue by yioannides** [rafaelmardojai/thunderbird-gnome-theme#18]
There have been some additional changes on v142 (still present on v147) that has broken the theme's layout, such as:

~~**1. the GNOME window buttons (style and padding):**~~ (most likely a flatpak-related upstream bug, [reported](https://bugzilla.mozilla.org/show_bug.cgi?id=2026112))

<img width="169" height="126" alt="Screenshot From 2025-08-26 19-23-19" src="https://github.com/user-attachments/assets/fb557e9e-c3c9-4453-9961-a2e6de5cf772" />

~~**2. the pane splitters in dark mode** (should be transparent, according to libadwaita 1.7+):~~ (fixed in #23)

<img width="775" height="540" alt="Screenshot From 2025-08-26 18-57-13" src="https://github.com/user-attachments/assets/5e0cb6b8-478b-428c-8a19-42f9c3eb0b5a" />

~~**3. no icons in the Reply window:**~~ (temp fix in https://github.com/rafaelmardojai/thunderbird-gnome-theme/issues/24#issuecomment-4041504862)

<img width="923" height="88" alt="Screenshot From 2025-08-26 18-57-35" src="https://github.com/user-attachments/assets/2bf533c6-7443-471a-a7f9-81a6c401c65a" />

~~**4. this artifact above Inbox in the mailbox pane** (appears in both light and dark mode):~~ (fixed in #23)

<img width="276" height="164" alt="Image" src="https://github.com/user-attachments/assets/8425c4ef-a72e-40a0-97b3-79b2c6484258" />

~~**5. the tabs have no top padding + the Search bar's text is right on the symbolic icon:**~~ (fixed in #23)

<img width="1823" height="148" alt="Image" src="https://github.com/user-attachments/assets/3b7d57a8-2232-478f-a9c8-d822e58138f4" />

**Comment by yioannides** [comment]
As commented in #16 by @LSeelig , the issue was slated to be resolved by v143, but it's still present in v147. Any ideas on how to approach this?

**Comment by yioannides** [comment]
The title buttons are still the same (as seen in the screenshot) with or without the theme, whereas Thunderbird's default symbolic icons are present in the Reply window, but not the theme's.

**Comment by LSeelig** [comment]
> The title buttons are still the same (as seen in the screenshot) with or without the theme, whereas Thunderbird's default symbolic icons are present in the Reply window, but not the theme's.

My title button is fixed, with or without the theme, though the height is slightly less than firefox or real libadwaita apps.

<img width="2254" height="198" alt="Image" src="https://github.com/user-attachments/assets/54732993-b617-4310-9182-528a733d6077" />

**Comment by LSeelig** [comment]
> [@LSeelig](https://github.com/LSeelig) Can you provide any extra info so we can maybe deduce what the issue might be? Like GNOME version, method of Thunderbird installation, system theme used etc. Also do you also now get the symbolic icons back in the Compose window?

Fedora 43, GNOME 49, DNF, adw-gtk3-wh (but identical to adw-gtk3 for dark). No symbolic icons in compose but I'm not using your most recent commits, just the @rafaelmardojai main.

<img width="2256" height="235" alt="Image" src="https://github.com/user-attachments/assets/b177d75b-eb0b-492f-9a2d-7e0d040556cf" />

Also, some symbolic icons outside of compose are still glitched. 

<img width="352" height="542" alt="Image" src="https://github.com/user-attachments/assets/41e218af-fa04-45fc-97c7-07d0b0f8ae3b" />

**Comment by yioannides** [comment]
> I may have had the flatpak at the time I took the dark screenshot so idk. Maybe theme? Using adw-gtk3?

I tried with and without adw-gtk3 and the problem persists. If anything, I think the Thunderbird theme overrides the system's `adw-gtk3` theme, but I'm not 100% sure.

**Comment by LSeelig** [comment]
> > I may have had the flatpak at the time I took the dark screenshot so idk. Maybe theme? Using adw-gtk3?
> 
> I tried with and without adw-gtk3 and the problem persists. If anything, I think the Thunderbird theme overrides the system's `adw-gtk3` theme, but I'm not 100% sure.

I forgot to mention I have some `about:config` values changed.
I also have a white headerbar because I disabled `widget.gtk.libadwaita-colors.enabled` in `about:config` and use [adw-gtk3-wh](https://github.com/LSeelig/adw-gtk3-white-headers). I don't think anything else changes and I tested with plain `adw-gtk3`.
Plus `widget.gtk.rounded-bottom-corners.enabled`

**Comment by LSeelig** [comment]
The

> > [@LSeelig](https://github.com/LSeelig) Can you provide any extra info so we can maybe deduce what the issue might be? Like GNOME version, method of Thunderbird installation, system theme used etc. Also do you also now get the symbolic icons back in the Compose window?
> 
> Fedora 43, GNOME 49, DNF, adw-gtk3-wh (but identical to adw-gtk3 for dark). No symbolic icons in compose but I'm not using your most recent commits, just the [@rafaelmardojai](https://github.com/rafaelmardojai) main.
> <img alt="Image" width="2000" height="235" src="https://private-user-images.githubusercontent.com/37001137/556455238-b177d75b-eb0b-492f-9a2d-7e0d040556cf.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM3MzU1NzMsIm5iZiI6MTc3MzczNTI3MywicGF0aCI6Ii8zNzAwMTEzNy81NTY0NTUyMzgtYjE3N2Q3NWItZWIwYi00OTJmLTlhMmQtN2UwZDA0MDU1NmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzE3VDA4MTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYmQwZjNlZTA1MjVhOWI1YTVmMzlhMTdlZWE5N2VkMTNiYTYwN2RmMjQ0Y2ZjYTM0NTI5MGQwNGNkZTNmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fK7HKtR9cmbQnwO6-LDdBqoSArG7naYqLT_DL09YQyg">
> 
> Also, some symbolic icons outside of compose are still glitched.
> <img alt="Image" width="352" height="542" src="https://private-user-images.githubusercontent.com/37001137/556455069-41e218af-fa04-45fc-97c7-07d0b0f8ae3b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM3MzU1NzMsIm5iZiI6MTc3MzczNTI3MywicGF0aCI6Ii8zNzAwMTEzNy81NTY0NTUwNjktNDFlMjE4YWYtZmEwNC00NWZjLTk3YzctMDdkMGIwZjhhZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzE3VDA4MTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4N2I0ODQ5MjAxN2EzYmY4NWZhOWJmYzdhZWFkODBjYWM4MzMxNzM1ZjcxMmNiYWFmZGIzYWFiMDAxMzJiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ux2fA-XijLSoA0ZuX-UTJ5JdI2EgVkKSbfCRmhdrJu8">

There's also a missing icon in the hidden image dialog for the close button, I think

<img width="1030" height="190" alt="Image" src="https://github.com/user-attachments/assets/6ced4fda-1b08-49be-8a30-e5c2e1d4dcd9" />
